### ISSUE TITLE
Gridlines don't meet at Celestial Poles

### ISSUE THREAD

**Issue by hemisemidemipresent** [steveberardi/starplot#104]
```py
from starplot import MapPlot, Projection
from starplot.styles import PlotStyle

p = MapPlot(
    projection=Projection.STEREO_NORTH,
    dec_min=35,
    dec_max=90,
    style=PlotStyle(),
)
p.gridlines() # add gridlines

p.export("n.png", padding=0.2, transparent=True)
```

![image](https://github.com/user-attachments/assets/6774e762-3444-4ec6-a437-45d6fe7c0697)

**Environment Details:**
- Starplot version: v0.11.4
- Python version: 3.11.8
- Matplotlib version: 3.9.2

**Comment by steveberardi** [comment]
Ahh, I've noticed this before, and previously thought it was something with cartopy/matplotlib, but it's a [bug in calculating the declination points](https://github.com/steveberardi/starplot/blob/main/src/starplot/map.py#L619) -- that list comprehension never includes `90`

I'm preparing v0.12.0 for release soon, so I'll fix this there.

Thanks for reporting this!

**Comment by steveberardi** [comment]
hmm, this may just be the way cartopy draws the gridlines, because when I fix that list comprehension to include 90 it still produces the same result. I also noticed [Cartopy has an example](https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/always_circular_stereo.html#sphx-glr-gallery-lines-and-polygons-always-circular-stereo-py) of a south polar stereo projection that shows the same behavior.

I do prefer the lines meeting at the poles though, so I'll look into another solution 👍
